name: "Local Rsync"
version: "0.1.0"
slug: "local_rsync"
description: "Run rsync between two local folders inside Home Assistant"
url: "https://github.com/KavajNaruj/ha-addon-local-rsync"
startup: "services"
boot: "auto"
init: false
homeassistant_api: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - type: share
    read_only: false
  - type: media
    read_only: false
options:
  run_mode: "once"
  schedule_minutes: 60
  jobs: []
schema:
  run_mode: "list(once|interval)"
  schedule_minutes: "int(1,)"
  jobs:
    - source: "str"
      destination: "str"
      args: "str?"
